name: Build and push Docker image

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - uses: little-core-labs/get-git-tag@v3.0.1
      id: tagName

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Load .env file
      id: dotenv
      uses: falti/dotenv-action@v1.1.2
      with:
        path: docker/build/.env
        log-variables: true
        export-variables: true
        
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker/build
        push: true
        tags: portablespark/docker-azure-spark:${{ github.ref_name }}
        build-args: |
          PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          SPARK_VERSION=${{ env.SPARK_VERSION }}
          DELTA_VERSION=${{ env.DELTA_VERSION }}
          HADOOP_VERSION=${{ env.HADOOP_VERSION }}
          HIVE_VERSION=${{ env.HIVE_VERSION }}
          LIVY_VERSION=${{ env.LIVY_VERSION }}
          DERBY_VERSION=${{ env.DERBY_VERSION }}