name: Build and push Docker image

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Extract Tag
      run:  |
            BRANCH_NAME=${GITHUB_REF#refs/tags/}
            echo $BRANCH_NAME
            # Replace slashes with dashes
            TAG=$(echo $BRANCH_NAME | tr '/' '-')
      shell: bash

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .devcontainer/docker
        push: true
        tags: portablespark/docker-azure-spark:${{ steps.extract_tag.outputs.tag }}
        build-args: |
          PYTHON_VERSION=${{ env.PYTHON_VERSION }}
          SPARK_VERSION=${{ env.SPARK_VERSION }}
          DELTA_VERSION=${{ env.DELTA_VERSION }} 
          HADOOP_VERSION=${{ env.HADOOP_VERSION }}