name: Build and push Docker image



on:
  workflow_dispatch:
    inputs:
      spark_version:
        description: 'Spark version to use'
        required: true
        type: string
        default: '3.5.0'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - uses: little-core-labs/get-git-tag@v3.0.1
      id: tagName

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Load .env file
      id: dotenv
      uses: falti/dotenv-action@v1.1.2
      with:
        path: docker/build/versions/${{ inputs.spark_version }}/.env
        log-variables: true
        export-variables: true

    - name: Build Docker image with context
      run: docker build -t dependencies:latest . -f docker/build/DependencyDockerfile --build-arg PYTHON_VERSION=${{ steps.dotenv.outputs.python_version }} --build-arg SPARK_VERSION=${{ steps.dotenv.outputs.spark_version }} --build-arg DELTA_VERSION=${{ steps.dotenv.outputs.delta_version }} --build-arg HADOOP_VERSION=${{ steps.dotenv.outputs.hadoop_version }} --build-arg HIVE_VERSION=${{ steps.dotenv.outputs.hive_version }} --build-arg LIVY_VERSION=${{ steps.dotenv.outputs.livy_version }} --build-arg DERBY_VERSION=${{ steps.dotenv.outputs.derby_version }} --build-arg JAVA_VERSION=${{ steps.dotenv.outputs.java_version }}


    - name: Create container from image
      run: docker create --name dependencies dependencies:latest

    - name: Copy artifacts from container
      run: docker cp dependencies:/path/to/artifacts ./artifacts

  use-artifacts:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download artifacts
      uses: actions/download-artifact@v2
      with:
        name: build-artifacts
        path: ./artifacts

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: docker/build
        push: true
        tags: portablespark/docker-azure-spark:${{ github.ref_name }}
        build-args: |
          PYTHON_VERSION=${{ steps.dotenv.outputs.python_version }}
          SPARK_VERSION=${{ steps.dotenv.outputs.spark_version }}
          DELTA_VERSION=${{ steps.dotenv.outputs.delta_version }}
          HADOOP_VERSION=${{ steps.dotenv.outputs.hadoop_version }}
          HIVE_VERSION=${{ steps.dotenv.outputs.hive_version }}
          LIVY_VERSION=${{ steps.dotenv.outputs.livy_version }}
          DERBY_VERSION=${{ steps.dotenv.outputs.derby_version }}
          JAVA_VERSION=${{ steps.dotenv.outputs.java_version }}
          ARTIFACTS_PATH=./artifacts 